### ISSUE TITLE
汉化问题(Sinicization problem)

### ISSUE THREAD

**Issue by WisteriaZy** [SlimefunGuguProject/AlchimiaVitae#26]
在注入分类的物品合成中,“一件有效的盔甲”和“一把有效的锄头”的物品描述中缺少“&”或“§”字符导致显示为"a可以是金、铁、钻石、下界合金材质”。
_另外“一把有效的钓竿”的物品描述“可以是钓竿”感觉有点多余（虽然原本可能就是这么描述的）_

**Comment by ybw0014** [comment]
已于新版本中修正
